---
- hosts: all
  tasks:
    - name: Create bash profile
      shell: touch ~/.bash_profile
      sudo: yes

    - name: Install curl
      apt: name=curl update_cache=yes
      sudo: yes

    - name: Install nvm
      shell: >
        curl https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | sh
        creates=/home/.nvm/nvm.sh

    - name: Install node and set version
      shell: >
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 4.2 && nvm alias default 4.2"
        creates=/home/.nvm/alias
